language: php

php: 7.2

git:
  depth: 150

cache:
  directories:
    - vendor

install:
  - phpenv config-rm xdebug.ini

before_script:
  - composer install -n

script:
  - vendor/bin/phpcs
  - vendor/bin/phpstan analyse -l 7 -c phpstan.neon.dist src
  - vendor/bin/phpunit
